project:
  type: book
  output-dir: docs

book:
  title: "R Workshop – Sozialwissenschaften"
  subtitle: "Einführung in die statistische Datenanalyse mit tidyverse und mariposa"
  author:
    - "Yannick Diehl"
    - "Daniel Moosdorf"
  date: today
  date-format: "DD.MM.YYYY"
  language: de
  search: true
  repo-url: https://github.com/RLoesung/RWorkshop
  repo-actions: [edit, source, issue]
  sidebar:
    style: floating
    collapse-level: 1
  chapters:
    - index.qmd
    - 01-RStudio.qmd
    - 02-ProgrammierspracheR.qmd
    - 03-Datenmodifikation.qmd
    - 04-Uni-Bivariate.Datenanalyse.qmd
    - 05-Multivariate.Datenanalyse.qmd
    - 06-Grafiken.erstellen.qmd

bibliography: [book.bib, packages.bib]

format:
  html:
    theme: [litera, theme.scss]
    css: style.css
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-tools: false
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    fig-align: center
    fig-cap-location: bottom
    smooth-scroll: true

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    comment: "##"
    collapse: true
    dpi: 150
    fig.align: center
    out.width: "90%"

lang: de
