{
  "hash": "7f6cddb7af14f3d57e52c787cddce4cc",
  "result": {
    "engine": "knitr",
    "markdown": "# Datenimport und Inspektion {#sec-datenimport}\n\n\n\n> *Wer trägt islamfeindliche Einstellungen in Deutschland 2023?*\n\nBevor du diese Frage beantworten kannst, brauchst du den Datensatz auf deinem Rechner — und du musst ihn so weit verstehen, dass du gezielt die richtigen Variablen herausziehen kannst. Dieses Kapitel begleitet dich vom Einlesen der SPSS-Datei über die ersten Inspektionsschritte bis zur sauberen Behandlung fehlender Werte. In @sec-datentransformation baust du dann auf diesem Fundament die zwei Skalen der Mini-Studie auf.\n\n## Worum es geht\n\nSekundärdaten kommen selten in der Form, in der du sie für eine konkrete Analyse brauchst. Der ALLBUS 2023 hat **579 Variablen** mit kryptischen Namen wie `mm01`, `pa29`, `wghtpew`. Vier verschiedene Missing-Codes laufen mit. Hinter jeder Spalte stehen zwei Label-Schichten (Variablenlabel und Wertelabel), die SPSS-Anwender:innen kennen und nicht verlieren wollen.\n\nDie *Datenmodifikation* ist in der quantitativen Sozialforschung kein Vorspann zur eigentlichen Analyse, sondern ihr methodischer Kern: über die Qualität jeder folgenden Auswertung wird hier entschieden. Wer in einem Forschungspapier eine *replizierbare* Analyse zeigen will, dokumentiert jeden Schritt — `read_spss()`, `set_na()`, `rec()`, `row_means()` — in einer einzigen Pipeline, die sich aus dem Skript heraus jederzeit nachvollziehen lässt.\n\nDieses Kapitel ist der **Anker** für die folgenden Methoden-Kapitel. Du legst hier den Datensatz an, mit dem du in @sec-univbivar Verteilungen beschreibst, in @sec-latente Strukturen prüfst und in @sec-erklaerung Hypothesen modellierst.\n\n## Was du nach diesem Kapitel kannst {-}\n\n- Einen SPSS-Datensatz mit `read_spss()` einlesen — inklusive aller Variablen- und Wertelabels.\n- Variablen über Name **oder** Label mit `find_var()` suchen.\n- Detail-Codebooks für ausgewählte Variablen mit `codebook()` erzeugen.\n- Variablen und Fälle gezielt auswählen, filtern, sortieren und umsortieren (`select()`, `filter()`, `arrange()`, `relocate()`).\n- Den `<haven_labelled>`-Datentyp verstehen und ihn bei Bedarf in Faktor oder numerisch konvertieren.\n- Variablenlabels und Wertelabels lesen, auslesen und setzen.\n- Fehlende Werte deklarieren und mit `na_frequencies()`, `set_na()` und `drop_na()` systematisch behandeln.\n\n## Setup\n\nIn jeder R-Sitzung lädst du zuerst die Pakete, mit denen du arbeitest. In diesem Buch sind das durchgehend nur zwei:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mariposa)\n```\n:::\n\n\n::: {.callout-tip}\n**SPSS → R.** In SPSS bist du gewohnt, dass alle Funktionen direkt verfügbar sind. In R aktivierst du dir mit `library()` gezielt die Werkzeuge, die du brauchst — das hält den Funktions-Namensraum übersichtlich und macht jeden Schritt nachvollziehbar.\n:::\n\n## Datensatz einlesen\n\nDer ALLBUS 2023 liegt als SPSS-Datei (`ALLBUS2023.sav`) im Projektordner. Mit `read_spss()` aus mariposa liest du sie ein:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus <- read_spss(\"ALLBUS2023.sav\")\n```\n:::\n\n\n`allbus` ist jetzt ein **Tibble** — ein moderner Datentyp im tidyverse. Tibbles verhalten sich wie klassische Data Frames, drucken aber kompakter und behalten ihre Spaltentypen besser. Was wir geladen haben:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,246 × 579\n   za_nr          doi   version respid substudy    mode    splt23_1    splt23_2 \n   <dbl+lbl>      <chr> <chr>    <dbl> <dbl+lbl>   <dbl+l> <dbl+lbl>   <dbl+lbl>\n 1 8831 [ALLBUSc… http… v1.3.0…      1 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   2 [SPL…\n 2 8831 [ALLBUSc… http… v1.3.0…      2     1 [SIM… 3 [CAW…     1 [SPL… -15 [TNZ…\n 3 8831 [ALLBUSc… http… v1.3.0…      3     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…\n 4 8831 [ALLBUSc… http… v1.3.0…      4     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…\n 5 8831 [ALLBUSc… http… v1.3.0…      5     2 [SEQ… 3 [CAW…     2 [SPL… -15 [TNZ…\n 6 8831 [ALLBUSc… http… v1.3.0…      6 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   1 [SPL…\n 7 8831 [ALLBUSc… http… v1.3.0…      7     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…\n 8 8831 [ALLBUSc… http… v1.3.0…      8     1 [SIM… 3 [CAW…     1 [SPL… -15 [TNZ…\n 9 8831 [ALLBUSc… http… v1.3.0…      9     2 [SEQ… 3 [CAW…     2 [SPL… -15 [TNZ…\n10 8831 [ALLBUSc… http… v1.3.0…     10 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   2 [SPL…\n# ℹ 5,236 more rows\n# ℹ 571 more variables: eastwest <dbl+lbl>, german <dbl+lbl>, ep01 <dbl+lbl>,\n#   ep03 <dbl+lbl>, ep04 <dbl+lbl>, ep06 <dbl+lbl>, xr19 <dbl+lbl>,\n#   xr20 <dbl+lbl>, lm27 <dbl+lbl>, lm28 <dbl+lbl>, lm29 <dbl+lbl>,\n#   lm30 <dbl+lbl>, lm31 <dbl+lbl>, lm32 <dbl+lbl>, lm33 <dbl+lbl>,\n#   lm34 <dbl+lbl>, la01 <dbl+lbl>, li01 <dbl+lbl>, li02 <dbl+lbl>,\n#   li03 <dbl+lbl>, li04 <dbl+lbl>, li05 <dbl+lbl>, li09 <dbl+lbl>, …\n```\n\n\n:::\n:::\n\n\nIm Kopf siehst du `5,246 × 579` — der Datensatz hat 5.246 Fälle und 579 Variablen. Darunter eine Auswahl der ersten Spalten mit ihren Datentypen.\n\n::: {.callout-note}\n**Hintergrund: Was passiert beim Einlesen?** `read_spss()` aus mariposa verwendet im Hintergrund das Paket `haven` und reichert die Daten mit zwei Eigenschaften an, die du aus SPSS kennst: **Variablenlabels** (eine ausführliche Beschriftung pro Spalte) und **Wertelabels** (eine Beschriftung pro Ausprägung). Beide Informationen bleiben unsichtbar in den Spalten gespeichert — du kannst sie jederzeit abrufen oder als Faktor sichtbar machen.\n:::\n\nFalls du Daten in anderen Formaten brauchst, gibt es passende Geschwister-Funktionen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nread_stata(\"datei.dta\")     # Stata\nread_sas(\"datei.sas7bdat\")  # SAS\nread_xlsx(\"datei.xlsx\")     # Excel\n```\n:::\n\n\nUnd wenn du einen bearbeiteten Datensatz zurück nach SPSS exportieren möchtest:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwrite_spss(allbus, \"allbus_bearbeitet.sav\")\n```\n:::\n\n\n## Erster Blick auf den Datensatz\n\nBei knapp 600 Variablen ist es unmöglich, sich alles in der Konsole anzeigen zu lassen. Drei Werkzeuge helfen dir bei der Orientierung:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(allbus)           # kompakte Strukturübersicht\nnrow(allbus)              # Anzahl Fälle\nncol(allbus)              # Anzahl Variablen\n```\n:::\n\n\n### Variablen finden mit `find_var()`\n\nDie Variablennamen im ALLBUS sind kryptisch (`mm01`, `pa29`, `wghtpew`). Was wirklich gemessen wird, steht im **Variablenlabel**. mariposas `find_var()` durchsucht beide gleichzeitig — Name und Label — und liefert dir die Treffer als kleine Übersichtstabelle:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |> find_var(\"muslim\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  col name                                    label\n1 194 mm03 ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT\n2 196 mm05   MUSLIMISCHER BUERGERMEISTER IN ORDNUNG\n3 197 mm06 UNTER MUSLIMEN SIND VIELE REL. FANATIKER\n```\n\n\n:::\n:::\n\n\nDamit findest du die sechs `mm`-Items für unsere Islamfeindlichkeits-Skala. Standardmäßig wird in Namen *und* Labels gesucht; mit `search = \"label\"` schränkst du auf Labels ein, mit `search = \"name\"` auf Namen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |> find_var(\"alter\", search = \"label\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   col    name                                    label\n1   93     age                       ALTER: BEFRAGTE(R)\n2   94    agec        ALTER: BEFRAGTE(R), KATEGORISIERT\n3  265    is01 PERSOENLICH.ALTERSSICHERUNG AUSREICHEND?\n4  311   dw12a      BEFR.: ALTER BEI AUFGABE DES BERUFS\n5  333   scage         GEGENWAERTIGER EHEPARTNER: ALTER\n6  334  scagec   GEGENWAERTIGER EHEPARTNER: ALTER, KAT.\n7  367    page                     LEBENSPARTNER: ALTER\n8  368   pagec               LEBENSPARTNER: ALTER, KAT.\n9  434  hh2age                    2.HAUSH.PERSON: ALTER\n10 439  hh3age                    3.HAUSH.PERSON: ALTER\n11 444  hh4age                    4.HAUSH.PERSON: ALTER\n12 449  hh5age                    5.HAUSH.PERSON: ALTER\n13 454  hh6age                    6.HAUSH.PERSON: ALTER\n14 459  hh7age                    7.HAUSH.PERSON: ALTER\n15 464  hh8age                    8.HAUSH.PERSON: ALTER\n16 471    dh17        ALTER JUENGSTES HAUSHALTSMITGLIED\n17 480  kh1age               ALTER, 1.KIND, AUSSER HAUS\n18 483  kh2age               ALTER, 2.KIND, AUSSER HAUS\n19 486  kh3age               ALTER, 3.KIND, AUSSER HAUS\n20 489  kh4age               ALTER, 4.KIND, AUSSER HAUS\n21 492  kh5age               ALTER, 5.KIND, AUSSER HAUS\n22 495  kh6age               ALTER, 6.KIND, AUSSER HAUS\n23 498  kh7age               ALTER, 7.KIND, AUSSER HAUS\n24 501  kh8age               ALTER, 8.KIND, AUSSER HAUS\n25 504  kh9age               ALTER, 9.KIND, AUSSER HAUS\n26 507 kh10age              ALTER, 10.KIND, AUSSER HAUS\n27 573    xi03                   INTERVIEWER(IN): ALTER\n```\n\n\n:::\n\n```{.r .cell-code}\nallbus |> find_var(\"^mm\", search = \"name\")     # regex: alle mm-Items\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  col name                                    label\n1 170 mm07        FUER DEN BAU VON MOSCHEEN IN BRD?\n2 192 mm01 ISLAMAUSUEBUNG IN DEUTSCHL. BESCHRAENKEN\n3 193 mm02 ISLAM PASST IN DIE DEUTSCHE GESELLSCHAFT\n4 194 mm03 ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT\n5 195 mm04   STAAT SOLLTE ISLAM. GRUPPEN BEOBACHTEN\n6 196 mm05   MUSLIMISCHER BUERGERMEISTER IN ORDNUNG\n7 197 mm06 UNTER MUSLIMEN SIND VIELE REL. FANATIKER\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**SPSS → R.** In SPSS kennst du `DISPLAY DICTIONARY` für eine Gesamtübersicht. `find_var()` ist gezielter: du suchst nach einem inhaltlichen Stichwort und bekommst sofort die passenden Variablen — selbst wenn du die kryptischen Namen nicht im Kopf hast.\n:::\n\n### Detail-Übersicht mit `codebook()`\n\nFür eine *bestimmte* Auswahl von Variablen liefert `codebook()` aus mariposa eine schöne HTML-Übersicht mit Labels, Ausprägungen und Häufigkeiten. Das ist das R-Äquivalent zum SPSS-`DISPLAY DICTIONARY`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  codebook(mm01, mm02, mm03, mm04, mm05, mm06)\n```\n:::\n\n\n::: {.callout-tip}\n**SPSS → R: Dateninspektion.**\n| SPSS                            | R                                |\n| ------------------------------- | -------------------------------- |\n| `FREQUENCIES VARIABLES=mm01.`   | `allbus \\|> frequency(mm01)`     |\n| `DESCRIPTIVES VARIABLES=age.`   | `allbus \\|> describe(age)`       |\n| `DISPLAY DICTIONARY.`           | `allbus \\|> codebook(...)`       |\n:::\n\n::: {.callout-note}\n**Reviewer-Hinweis.** In einer Methodenbeschreibung gehört zu jeder Skala ein Mini-Codebook: Wortlaut der Items, Antwortformat, Missing-Behandlung, N pro Item. Wer das in `codebook()` als Tabelle generiert und in den Anhang seines Berichts schreibt, hat den Forschungsstandard erfüllt.\n:::\n\n## Variablen und Fälle auswählen\n\nDie `dplyr`-Funktionen `select()`, `filter()` und `arrange()` sind dein tägliches Werkzeug, um aus einem großen Datensatz das herauszuholen, was du gerade brauchst.\n\n### Variablen auswählen mit `select()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(mm01, mm02, mm03)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,246 × 3\n   mm01                        mm02                        mm03              \n   <dbl+lbl>                   <dbl+lbl>                   <dbl+lbl>         \n 1     5 [..]                      3 [..]                      4 [..]        \n 2 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]\n 3 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]\n 4 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]\n 5     2 [..]                      4 [..]                      4 [..]        \n 6     3 [..]                      3 [..]                      3 [..]        \n 7 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]\n 8 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]\n 9     1 [STIMME GAR NICHT ZU]     6 [..]                      2 [..]        \n10     7 [STIMME VOLL+GANZ ZU]     1 [STIMME GAR NICHT ZU]     3 [..]        \n# ℹ 5,236 more rows\n```\n\n\n:::\n:::\n\n\nDu kannst Bereiche mit `:` angeben und Variablen mit `-` ausschließen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(mm01:mm06, eastwest, sex, age, educ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,246 × 10\n   mm01              mm02        mm03        mm04        mm05        mm06       \n   <dbl+lbl>         <dbl+lbl>   <dbl+lbl>   <dbl+lbl>   <dbl+lbl>   <dbl+lbl>  \n 1     5 [..]            3 [..]      4 [..]      2 [..]      6 [..]      2 [..] \n 2 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…\n 3 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…\n 4 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…\n 5     2 [..]            4 [..]      4 [..]      3 [..]      3 [..]      6 [..] \n 6     3 [..]            3 [..]      3 [..]      7 [STI…     6 [..]      3 [..] \n 7 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…\n 8 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…\n 9     1 [STIMME GA…     6 [..]      2 [..]      1 [STI…     7 [STI…     2 [..] \n10     7 [STIMME VO…     1 [STI…     3 [..]      6 [..]      1 [STI…     7 [STI…\n# ℹ 5,236 more rows\n# ℹ 4 more variables: eastwest <dbl+lbl>, sex <dbl+lbl>, age <dbl+lbl>,\n#   educ <dbl+lbl>\n```\n\n\n:::\n:::\n\n\nDiese Auswahl — die sechs Skalen-Items plus Demografie — ist genau das, was du für die Mini-Studie brauchst.\n\nZwei nahe Verwandte von `select()`:\n\n- **`pull(var)`** zieht eine einzelne Spalte als reinen Vektor heraus — nützlich, wenn du den Spalteninhalt direkt in eine Funktion füttern willst, die kein Tibble erwartet: `allbus |> pull(age) |> mean(na.rm = TRUE)`.\n- **`relocate(var, .before = X, .after = Y)`** sortiert Spalten um, ohne welche zu entfernen — praktisch, wenn die wichtigsten Variablen vorne stehen sollen: `allbus |> relocate(islamophobie, populismus, .before = sex)`.\n\n### Fälle filtern mit `filter()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  filter(sex == 2) |>\n  select(sex, age, educ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,672 × 3\n   sex       age       educ                  \n   <dbl+lbl> <dbl+lbl> <dbl+lbl>             \n 1 2 [FRAU]  69        4 [FACHHOCHSCHULREIFE]\n 2 2 [FRAU]  18        5 [HOCHSCHULREIFE]    \n 3 2 [FRAU]  45        5 [HOCHSCHULREIFE]    \n 4 2 [FRAU]  26        3 [MITTLERE REIFE]    \n 5 2 [FRAU]  71        2 [VOLKS-,HAUPTSCHULE]\n 6 2 [FRAU]  66        2 [VOLKS-,HAUPTSCHULE]\n 7 2 [FRAU]  39        3 [MITTLERE REIFE]    \n 8 2 [FRAU]  51        3 [MITTLERE REIFE]    \n 9 2 [FRAU]  29        5 [HOCHSCHULREIFE]    \n10 2 [FRAU]  60        4 [FACHHOCHSCHULREIFE]\n# ℹ 2,662 more rows\n```\n\n\n:::\n:::\n\n\nDie Vergleichs- und Logik-Operatoren aus @sec-operatoren (`==`, `!=`, `<`, `>`, `&`, `|`, `%in%`) bilden hier dein Vokabular. Komplexere Filter kombinierst du frei:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  filter(eastwest == 2 & age >= 30 & age <= 60) |>\n  select(eastwest, age, educ) |>\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 825\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n**Vorsicht: Fehlende Werte.** `filter()` schließt Fälle mit `NA` in der Bedingung automatisch aus. Das ist meist gewünscht, kann dich aber überraschen. Mit `filter(is.na(variable))` filterst du gezielt *fehlende* Werte heraus.\n:::\n\n### Fälle sortieren mit `arrange()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(age, educ) |>\n  arrange(age) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  age       educ                  \n  <dbl+lbl> <dbl+lbl>             \n1 18        5 [HOCHSCHULREIFE]    \n2 18        5 [HOCHSCHULREIFE]    \n3 18        3 [MITTLERE REIFE]    \n4 18        1 [OHNE ABSCHLUSS]    \n5 18        2 [VOLKS-,HAUPTSCHULE]\n```\n\n\n:::\n:::\n\n\nAbsteigend mit `desc()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(age, educ) |>\n  arrange(desc(age)) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  age       educ                  \n  <dbl+lbl> <dbl+lbl>             \n1 99        2 [VOLKS-,HAUPTSCHULE]\n2 97        5 [HOCHSCHULREIFE]    \n3 97        5 [HOCHSCHULREIFE]    \n4 94        2 [VOLKS-,HAUPTSCHULE]\n5 94        4 [FACHHOCHSCHULREIFE]\n```\n\n\n:::\n:::\n\n\n## Datentypen verstehen\n\nBeim Einlesen von SPSS-Dateien erhältst du Spalten mit dem speziellen Typ `<haven_labelled>`. Sie verhalten sich wie Zahlen, tragen aber die Wertelabels mit. Mit `class()` siehst du den Typ einer Variable:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclass(allbus$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"haven_labelled\" \"vctrs_vctr\"     \"double\"        \n```\n\n\n:::\n\n```{.r .cell-code}\nclass(allbus$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"haven_labelled\" \"vctrs_vctr\"     \"double\"        \n```\n\n\n:::\n:::\n\n\nDrei Konvertierungen wirst du immer wieder brauchen:\n\n| Funktion                              | Wirkung                                                                                                                       |\n| ------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------- |\n| `to_label(data, var)`                 | wandelt `<haven_labelled>` in einen **Faktor** mit den Wertelabels als Stufen — Standard, wenn du in `ggplot()`-Achsen lesbare Beschriftungen willst |\n| `to_numeric(data, var)`               | wandelt in einen reinen numerischen Vektor — Labels gehen verloren                                                            |\n| `to_labelled(data, var, labels = ...)`| wandelt umgekehrt einen Faktor zurück in ein `<haven_labelled>`                                                              |\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  to_label(sex, eastwest) |>\n  select(sex, eastwest) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  sex   eastwest          \n  <fct> <fct>             \n1 MANN  ALTE BUNDESLAENDER\n2 MANN  ALTE BUNDESLAENDER\n3 FRAU  ALTE BUNDESLAENDER\n```\n\n\n:::\n:::\n\n\nWenn du nur Labels *abstreifen* willst (z. B. weil eine Funktion mit labelled-Vektoren nicht klarkommt), nimmst du `unlabel()`: `allbus |> unlabel(sex, age)`. Selten gebraucht, aber gut zu wissen, wenn ein fremdes Paket sich quer stellt.\n\n::: {.callout-note}\n**Hintergrund: Warum nicht einfach Faktor?** In SPSS sind Variablen entweder numerisch oder *string*. Wertelabels sind ein Zusatz. In R gibt es Faktoren (Kategorien) und numerische Vektoren als getrennte Typen. `<haven_labelled>` ist eine Brücke: Du arbeitest mit Zahlen, aber die Wertelabels reisen mit. Wann du das auflösen solltest:\n\n- **`to_label()`** wenn du sortierst, gruppierst, kreuztabellierst oder plottest — Faktoren liefern lesbare Outputs.\n- **`to_numeric()`** wenn du rechnest oder skalierst — z. B. bei Likert-Items, die du als pseudo-metrisch behandelst.\n- **Beim Original lassen**, wenn die Variable noch nicht final ist und du das Label später noch brauchst.\n:::\n\n## Variablen- und Wertelabels lesen und setzen\n\n| Funktion                                            | Wirkung                                                              |\n| --------------------------------------------------- | -------------------------------------------------------------------- |\n| `var_label(data)`                                   | Variablenlabels auslesen                                             |\n| `var_label(data) <- list(var = \"Neue Beschriftung\")`| Variablenlabel setzen                                                |\n| `val_labels(data)`                                  | Wertelabels auslesen                                                 |\n| `drop_labels(data)`                                 | Alle Wertelabels entfernen, deren Ausprägung in den Daten gar nicht vorkommt |\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(mm01, mm02, mm03) |>\n  var_label()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      mm01 \n\"ISLAMAUSUEBUNG IN DEUTSCHL. BESCHRAENKEN\" \n                                      mm02 \n\"ISLAM PASST IN DIE DEUTSCHE GESELLSCHAFT\" \n                                      mm03 \n\"ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT\" \n```\n\n\n:::\n:::\n\n\nDas Ergebnis ist ein **benannter Character-Vektor** — pro Variable das hinterlegte Label. So liest du, was eine kryptische Variable wie `mm01` eigentlich bedeutet, ohne ins Codebook zu schauen.\n\n## Fehlende Werte deklarieren\n\nALLBUS verwendet negative Codes für verschiedene Arten fehlender Werte:\n\n| Code  | Bedeutung                                |\n| ----: | ---------------------------------------- |\n| `-42` | DATENFEHLER                              |\n| `-11` | TNZ (trifft nicht zu / Split-Modul)      |\n| `-9`  | KEINE ANGABE                             |\n| `-8`  | WEISS NICHT                              |\n\nBeim Einlesen werden diese in SPSS als *user-missing* deklarierten Codes automatisch zu **tagged NAs**. Das bedeutet: Sie zählen in Berechnungen als `NA`, behalten aber ihre ursprüngliche Information.\n\n::: {.callout-note}\n**Hintergrund: Split-Designs im ALLBUS.** Manche Itembatterien werden nur einer Hälfte der Stichprobe gestellt (Code `-11` für die andere Hälfte). Das gilt insbesondere für die `mm`-Items unserer Islamfeindlichkeits-Skala. Die effektive N für solche Splits liegt deshalb bei rund 2.500 statt 5.246 — methodisch *kein* Fehler, sondern Stichproben­architektur. In der Methodenbeschreibung gehört dieser Punkt erwähnt.\n:::\n\nWie viele Fälle pro Missing-Code in einer konkreten Variable stecken, zeigt dir `na_frequencies()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nna_frequencies(allbus$mm01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   tag    n code            label\n1    b 1647  -11       TNZ: SPLIT\n2    d  123   -8      WEISS NICHT\n3    c   73   -9     KEINE ANGABE\n4    a    2  -42 DATENFEHLER: MFN\n5 <NA>    0 <NA> (System Missing)\n```\n\n\n:::\n:::\n\n\nDu siehst die Aufschlüsselung: wie viele „weiß nicht\", wie viele „keine Angabe\", wie viele „trifft nicht zu\" — alles in einem Aufruf. Praktisch, bevor du entscheidest, ob du bestimmte Codes als reguläre Werte behältst oder als endgültige Missings behandelst.\n\nWenn du eine Variable hast, in der bestimmte Werte *erst nachträglich* als fehlend gelten sollen — etwa Altersangaben über 100 als unplausibel —, deklarierst du sie mit `set_na()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  set_na(age, na_values = c(-9, -8), verbose = TRUE)\n```\n:::\n\n\nMit `verbose = TRUE` zeigt mariposa dir an, wie viele Fälle pro Wert zu `NA` wurden — kontrolliert und nachvollziehbar.\n\nMit `drop_na()` (aus tidyr) entfernst du Fälle mit `NA`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  select(mm01, mm02, mm03) |>\n  drop_na() |>\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3285\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n**Vorsicht: Listenweiser Ausschluss.** `drop_na()` schließt Fälle aus, sobald *eine* der ausgewählten Variablen `NA` ist. Das ist klassischer *listwise deletion*. Wenn du in einer großen Pipeline mit vielen Variablen `drop_na()` rufst, kann deine Fallzahl drastisch schrumpfen. Setze `drop_na()` deshalb gezielt auf die Variablen, die du wirklich brauchst.\n:::\n\n::: {.callout-note}\n**Hintergrund: MCAR, MAR, MNAR.** Die Methodenliteratur unterscheidet drei Missing-Mechanismen: *Missing Completely at Random* (Zufall, keine Verzerrung), *Missing at Random* (Zufall bedingt durch beobachtete Variablen, durch Modellierung korrigierbar) und *Missing Not at Random* (systematisch, schwer zu beheben). In Survey-Daten wie ALLBUS ist MAR der Regelfall; einfache Listwise Deletion (`drop_na()`) ist dann ein konservativer, aber transparenter Umgang. Imputationsverfahren (z. B. `mice`) sind die nächste Ausbaustufe — für ein Einsteigerbuch jedoch zu viel.\n:::\n\n## Übungen {-}\n\n::: {.callout-tip collapse=\"true\"}\n**Übung 1 — Variablen finden (Reproduktion).** Du willst eine Skala zu Vertrauen in Institutionen bauen, kennst aber die Variablennamen nicht auswendig. Nutze `find_var()`, um (a) alle Variablen mit „vertrau\" im Label und (b) alle Variablen mit `st` am Namensanfang zu finden.\n\n**Lösung:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |> find_var(\"vertrau\", search = \"label\")\nallbus |> find_var(\"^st\", search = \"name\")\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n**Übung 2 — Codebook der politischen Vertrauens-Items (Reproduktion).** Erstelle ein `codebook()` für die Items `pt01` bis `pt08` (Vertrauen in verschiedene Institutionen). Schau dir Labels und Wertelabels an.\n\n**Lösung:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nallbus |>\n  codebook(pt01, pt02, pt03, pt04, pt05, pt06, pt07, pt08)\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n**Übung 3 — Analyse-Subset bilden (Transfer).** Erstelle einen Datensatz `analyse`, der nur die für die Mini-Studie nötigen Variablen enthält (`mm01:mm06`, `pa29:pa35`, `eastwest`, `sex`, `age`, `educ`, `wghtpew`) und nur Fälle, in denen mindestens fünf der sechs `mm`-Items gültig sind. *Tipp: `rowSums(!is.na(across(mm01:mm06))) >= 5` als Filterkriterium.*\n\n**Lösung:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanalyse <- allbus |>\n  select(mm01:mm06, pa29:pa35, eastwest, sex, age, educ, wghtpew) |>\n  filter(rowSums(!is.na(across(mm01:mm06))) >= 5)\nnrow(analyse)\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n**Übung 4 — Eigene Forschungsfrage.** Wähle ein Thema, das dich politik- oder sozialwissenschaftlich interessiert (Migration, Klima, Geschlechterrollen, …). Finde mit `find_var()` zwei bis drei Variablen im ALLBUS 2023, die deine Frage beleuchten könnten. Erstelle ein `codebook()` für deine Auswahl. Beschreibe in 2–3 Sätzen, was du untersuchen würdest und welche Variable als unabhängige bzw. abhängige Variable dienen könnte.\n\n*Es gibt hier keine Musterlösung — die Übung trainiert das Auffinden und Verstehen von Variablen, nicht eine bestimmte Antwort.*\n:::\n\n## Was du jetzt weißt {-}\n\n- Du liest SPSS-Daten mit `read_spss()` ein und behältst Variablen- und Wertelabels.\n- Du findest Variablen über Name oder Label mit `find_var()` und holst dir Detail-Codebooks per `codebook()`.\n- Du wählst Variablen und Fälle mit `select()`, `filter()`, `arrange()` aus — und sortierst sie mit `relocate()` um.\n- Du verstehst den `<haven_labelled>`-Typ und wandelst ihn bei Bedarf in Faktor oder numerisch.\n- Du liest und setzt Variablen- und Wertelabels mit `var_label()` und `val_labels()`.\n- Du erkennst die ALLBUS-Missing-Codes, prüfst sie mit `na_frequencies()` und schließt Fälle gezielt aus.\n\nIm nächsten Kapitel (@sec-datentransformation) lernst du, wie du aus diesen Rohvariablen die zwei Skalen baust, die die Mini-Studie trägt — Islamfeindlichkeit und Populismus.\n\n## Weiterführend {-}\n\n- mariposa-Vignetten [„Data I/O\"](https://yannickdiehl.github.io/mariposa/articles/data-io.html) und [„Labels and Missing Values\"](https://yannickdiehl.github.io/mariposa/articles/labels-and-missing-values.html).\n- Hadley Wickham & Garrett Grolemund, [R for Data Science (2e), Kapitel „Data Import\" und „Data Transformation\"](https://r4ds.hadley.nz/data-import.html).\n- Joseph Larmarange, [„labelled\" Vignetten](https://larmarange.github.io/labelled/) — vertiefte Auseinandersetzung mit labelled-Datentypen.\n- GESIS, [Datensatzbeschreibung ALLBUS 2023 (ZA8901)](https://search.gesis.org/research_data/ZA8901) — Methodenbericht und Codeplan.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}