<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>4&nbsp; Datenimport und Inspektion – R Workshop – Sozialwissenschaften</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-Datentransformation.html" rel="next">
<link href="./03-ProgrammierspracheR.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6499386a99bca6986a49a1d91551f074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-Datenimport.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Datenimport und Inspektion</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R Workshop – Sozialwissenschaften</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/RLoesung/RWorkshop" title="Quellcode" class="quarto-navigation-tool px-1" aria-label="Quellcode"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Quarto und reproduzierbare Wissenschaft</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-ProgrammierspracheR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Programmiersprache R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Datenimport.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Datenimport und Inspektion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Datentransformation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Daten transformieren und Skalen bilden</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Grafiken-Grundlagen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Visualisierung — Grundlagen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Uni-Bivariate-Analyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Uni- und Bivariate Analyse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Latente-Strukturen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Latente Strukturen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Erklaerungsmodelle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Erklärungsmodelle</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="-1"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li><a href="#worum-es-geht" id="toc-worum-es-geht" class="nav-link active" data-scroll-target="#worum-es-geht"><span class="header-section-number">4.1</span> Worum es geht</a></li>
  <li><a href="#was-du-nach-diesem-kapitel-kannst" id="toc-was-du-nach-diesem-kapitel-kannst" class="nav-link" data-scroll-target="#was-du-nach-diesem-kapitel-kannst">Was du nach diesem Kapitel kannst</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">4.2</span> Setup</a></li>
  <li><a href="#datensatz-einlesen" id="toc-datensatz-einlesen" class="nav-link" data-scroll-target="#datensatz-einlesen"><span class="header-section-number">4.3</span> Datensatz einlesen</a></li>
  <li>
<a href="#erster-blick-auf-den-datensatz" id="toc-erster-blick-auf-den-datensatz" class="nav-link" data-scroll-target="#erster-blick-auf-den-datensatz"><span class="header-section-number">4.4</span> Erster Blick auf den Datensatz</a>
  <ul>
<li><a href="#variablen-finden-mit-find_var" id="toc-variablen-finden-mit-find_var" class="nav-link" data-scroll-target="#variablen-finden-mit-find_var"><span class="header-section-number">4.4.1</span> Variablen finden mit <code>find_var()</code></a></li>
  <li><a href="#detail-%C3%BCbersicht-mit-codebook" id="toc-detail-übersicht-mit-codebook" class="nav-link" data-scroll-target="#detail-%C3%BCbersicht-mit-codebook"><span class="header-section-number">4.4.2</span> Detail-Übersicht mit <code>codebook()</code></a></li>
  </ul>
</li>
  <li>
<a href="#variablen-und-f%C3%A4lle-ausw%C3%A4hlen" id="toc-variablen-und-fälle-auswählen" class="nav-link" data-scroll-target="#variablen-und-f%C3%A4lle-ausw%C3%A4hlen"><span class="header-section-number">4.5</span> Variablen und Fälle auswählen</a>
  <ul>
<li><a href="#variablen-ausw%C3%A4hlen-mit-select" id="toc-variablen-auswählen-mit-select" class="nav-link" data-scroll-target="#variablen-ausw%C3%A4hlen-mit-select"><span class="header-section-number">4.5.1</span> Variablen auswählen mit <code>select()</code></a></li>
  <li><a href="#f%C3%A4lle-filtern-mit-filter" id="toc-fälle-filtern-mit-filter" class="nav-link" data-scroll-target="#f%C3%A4lle-filtern-mit-filter"><span class="header-section-number">4.5.2</span> Fälle filtern mit <code>filter()</code></a></li>
  <li><a href="#f%C3%A4lle-sortieren-mit-arrange" id="toc-fälle-sortieren-mit-arrange" class="nav-link" data-scroll-target="#f%C3%A4lle-sortieren-mit-arrange"><span class="header-section-number">4.5.3</span> Fälle sortieren mit <code>arrange()</code></a></li>
  </ul>
</li>
  <li><a href="#datentypen-verstehen" id="toc-datentypen-verstehen" class="nav-link" data-scroll-target="#datentypen-verstehen"><span class="header-section-number">4.6</span> Datentypen verstehen</a></li>
  <li><a href="#variablen--und-wertelabels-lesen-und-setzen" id="toc-variablen--und-wertelabels-lesen-und-setzen" class="nav-link" data-scroll-target="#variablen--und-wertelabels-lesen-und-setzen"><span class="header-section-number">4.7</span> Variablen- und Wertelabels lesen und setzen</a></li>
  <li><a href="#fehlende-werte-deklarieren" id="toc-fehlende-werte-deklarieren" class="nav-link" data-scroll-target="#fehlende-werte-deklarieren"><span class="header-section-number">4.8</span> Fehlende Werte deklarieren</a></li>
  <li><a href="#%C3%BCbungen" id="toc-übungen" class="nav-link" data-scroll-target="#%C3%BCbungen">Übungen</a></li>
  <li><a href="#was-du-jetzt-wei%C3%9Ft" id="toc-was-du-jetzt-weißt" class="nav-link" data-scroll-target="#was-du-jetzt-wei%C3%9Ft">Was du jetzt weißt</a></li>
  <li><a href="#weiterf%C3%BChrend" id="toc-weiterführend" class="nav-link" data-scroll-target="#weiterf%C3%BChrend">Weiterführend</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/RLoesung/RWorkshop/edit/main/04-Datenimport.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/RLoesung/RWorkshop/blob/main/04-Datenimport.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li><li><a href="https://github.com/RLoesung/RWorkshop/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-datenimport" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Datenimport und Inspektion</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><blockquote class="blockquote">
<p><em>Wer trägt islamfeindliche Einstellungen in Deutschland 2023?</em></p>
</blockquote>
<p>Bevor du diese Frage beantworten kannst, brauchst du den Datensatz auf deinem Rechner — und du musst ihn so weit verstehen, dass du gezielt die richtigen Variablen herausziehen kannst. Dieses Kapitel begleitet dich vom Einlesen der SPSS-Datei über die ersten Inspektionsschritte bis zur sauberen Behandlung fehlender Werte. In <a href="05-Datentransformation.html" class="quarto-xref"><span>Kapitel 5</span></a> baust du dann auf diesem Fundament die zwei Skalen der Mini-Studie auf.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Forschungsjournal: Wo stehst du in deiner Mini-Studie?</strong> Werkzeug steht (Kap. 1–3). Jetzt beginnt die <em>eigentliche</em> Forschungsarbeit. Mit diesem Kapitel hältst du am Ende einen Analyse-Datensatz in der Hand: 5.246 Befragte, dein eigenes Variablenset, fehlende Werte deklariert. Das ist der Rohzustand, von dem aus alle weiteren Etappen aufbauen.</p>
</div>
</div>
<section id="worum-es-geht" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="worum-es-geht">
<span class="header-section-number">4.1</span> Worum es geht</h2>
<p>Stell dir vor, du bekommst von einer Kollegin einen USB-Stick mit der Aufschrift <em>„ALLBUS 2023 — viel Spaß”</em>. Du steckst ihn ein und öffnest die Datei. Was du siehst, ist nicht das, was du dir erhofft hast: 579 Spalten mit Namen wie <code>mm01</code>, <code>pa29</code>, <code>pt06</code>, <code>wghtpew</code>. Vier verschiedene negative Zahlen tauchen als „Wert” auf — <code>-9</code>, <code>-11</code>, <code>-42</code>. Manche Variablen sind als Zahl gespeichert, obwohl sie eigentlich eine Kategorie sind (<code>sex = 1</code> heißt „Mann”). Und die wirklichen Beschriftungen — das, was tatsächlich gefragt wurde — liegen irgendwo versteckt, unsichtbar im Hintergrund.</p>
<p>Genau dieser Zustand ist normal. Sekundärdatensätze aus der quantitativen Sozialforschung sehen <em>immer</em> so aus. Sie sind so gebaut, dass viele Menschen sie für viele unterschiedliche Fragen nutzen können — und das geht nur, wenn die Daten zunächst <em>roh</em> bleiben. Deine Aufgabe ist es, aus diesem Rohzustand einen Analyse-Datensatz zu machen, der zu <em>deiner</em> Forschungsfrage passt.</p>
<p>Diese Schritte sind keine Vorarbeit, die man möglichst schnell hinter sich bringt. Sie sind der methodische Kern jeder ehrlichen Auswertung: Welche Fälle nimmst du raus? Wie behandelst du fehlende Werte? Wie übersetzt du <code>mm01 = 7</code> in „diese Person lehnt Muslime stark ab”? Jede dieser Entscheidungen beeinflusst, was am Ende rauskommt — und jede gehört in eine Pipeline, die du jederzeit reproduzieren kannst. <em>Das</em> ist offene Wissenschaft im konkreten Handwerk.</p>
<p>Dieses Kapitel ist der <strong>Anker</strong> für alles, was folgt. Du legst hier den Analyse-Datensatz an, mit dem du in <a href="07-Uni-Bivariate-Analyse.html" class="quarto-xref"><span>Kapitel 7</span></a> Verteilungen beschreibst, in <a href="08-Latente-Strukturen.html" class="quarto-xref"><span>Kapitel 8</span></a> Strukturen prüfst und in <a href="09-Erklaerungsmodelle.html" class="quarto-xref"><span>Kapitel 9</span></a> Hypothesen modellierst. Wenn dieser Anker hält, halten alle späteren Befunde.</p>
</section><section id="was-du-nach-diesem-kapitel-kannst" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="was-du-nach-diesem-kapitel-kannst">Was du nach diesem Kapitel kannst</h2>
<ul>
<li>Einen SPSS-Datensatz mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/read_spss.html">read_spss()</a></code> einlesen — inklusive aller Variablen- und Wertelabels.</li>
<li>Variablen über Name <strong>oder</strong> Label mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code> suchen.</li>
<li>Detail-Codebooks für ausgewählte Variablen mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code> erzeugen.</li>
<li>Variablen und Fälle gezielt auswählen, filtern, sortieren und umsortieren (<code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/relocate.html">relocate()</a></code>).</li>
<li>Den <code>&lt;haven_labelled&gt;</code>-Datentyp verstehen und ihn bei Bedarf in Faktor oder numerisch konvertieren.</li>
<li>Variablenlabels und Wertelabels lesen, auslesen und setzen.</li>
<li>Fehlende Werte deklarieren und mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/na_frequencies.html">na_frequencies()</a></code>, <code><a href="https://YannickDiehl.github.io/mariposa/reference/set_na.html">set_na()</a></code> und <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code> systematisch behandeln.</li>
</ul></section><section id="setup" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="setup">
<span class="header-section-number">4.2</span> Setup</h2>
<p>In jeder R-Sitzung lädst du zuerst die Pakete, mit denen du arbeitest. In diesem Buch sind das durchgehend nur zwei:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://YannickDiehl.github.io/mariposa/">mariposa</a></span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>SPSS → R.</strong> In SPSS bist du gewohnt, dass alle Funktionen direkt verfügbar sind. In R aktivierst du dir mit <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> gezielt die Werkzeuge, die du brauchst — das hält den Funktions-Namensraum übersichtlich und macht jeden Schritt nachvollziehbar.</p>
</div>
</div>
</section><section id="datensatz-einlesen" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="datensatz-einlesen">
<span class="header-section-number">4.3</span> Datensatz einlesen</h2>
<p>Der ALLBUS 2023 liegt als SPSS-Datei (<code>ALLBUS2023.sav</code>) im Projektordner. Mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/read_spss.html">read_spss()</a></code> aus mariposa liest du sie ein:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/read_spss.html">read_spss</a></span><span class="op">(</span><span class="st">"ALLBUS2023.sav"</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>allbus</code> ist jetzt ein <strong>Tibble</strong> — ein moderner Datentyp im tidyverse. Tibbles verhalten sich wie klassische Data Frames, drucken aber kompakter und behalten ihre Spaltentypen besser. Was wir geladen haben:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,246 × 579
   za_nr          doi   version respid substudy    mode    splt23_1    splt23_2 
   &lt;dbl+lbl&gt;      &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl+lbl&gt;   &lt;dbl+l&gt; &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;
 1 8831 [ALLBUSc… http… v1.3.0…      1 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   2 [SPL…
 2 8831 [ALLBUSc… http… v1.3.0…      2     1 [SIM… 3 [CAW…     1 [SPL… -15 [TNZ…
 3 8831 [ALLBUSc… http… v1.3.0…      3     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…
 4 8831 [ALLBUSc… http… v1.3.0…      4     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…
 5 8831 [ALLBUSc… http… v1.3.0…      5     2 [SEQ… 3 [CAW…     2 [SPL… -15 [TNZ…
 6 8831 [ALLBUSc… http… v1.3.0…      6 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   1 [SPL…
 7 8831 [ALLBUSc… http… v1.3.0…      7     1 [SIM… 4 [MAI…     1 [SPL… -15 [TNZ…
 8 8831 [ALLBUSc… http… v1.3.0…      8     1 [SIM… 3 [CAW…     1 [SPL… -15 [TNZ…
 9 8831 [ALLBUSc… http… v1.3.0…      9     2 [SEQ… 3 [CAW…     2 [SPL… -15 [TNZ…
10 8831 [ALLBUSc… http… v1.3.0…     10 NA(a) [TNZ… 2 [CAP… NA(a) [TNZ…   2 [SPL…
# ℹ 5,236 more rows
# ℹ 571 more variables: eastwest &lt;dbl+lbl&gt;, german &lt;dbl+lbl&gt;, ep01 &lt;dbl+lbl&gt;,
#   ep03 &lt;dbl+lbl&gt;, ep04 &lt;dbl+lbl&gt;, ep06 &lt;dbl+lbl&gt;, xr19 &lt;dbl+lbl&gt;,
#   xr20 &lt;dbl+lbl&gt;, lm27 &lt;dbl+lbl&gt;, lm28 &lt;dbl+lbl&gt;, lm29 &lt;dbl+lbl&gt;,
#   lm30 &lt;dbl+lbl&gt;, lm31 &lt;dbl+lbl&gt;, lm32 &lt;dbl+lbl&gt;, lm33 &lt;dbl+lbl&gt;,
#   lm34 &lt;dbl+lbl&gt;, la01 &lt;dbl+lbl&gt;, li01 &lt;dbl+lbl&gt;, li02 &lt;dbl+lbl&gt;,
#   li03 &lt;dbl+lbl&gt;, li04 &lt;dbl+lbl&gt;, li05 &lt;dbl+lbl&gt;, li09 &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<p>Im Kopf siehst du <code>5,246 × 579</code> — der Datensatz hat 5.246 Fälle und 579 Variablen. Darunter eine Auswahl der ersten Spalten mit ihren Datentypen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hintergrund: Was passiert beim Einlesen?</strong> <code><a href="https://YannickDiehl.github.io/mariposa/reference/read_spss.html">read_spss()</a></code> aus mariposa verwendet im Hintergrund das Paket <code>haven</code> und reichert die Daten mit zwei Eigenschaften an, die du aus SPSS kennst: <strong>Variablenlabels</strong> (eine ausführliche Beschriftung pro Spalte) und <strong>Wertelabels</strong> (eine Beschriftung pro Ausprägung). Beide Informationen bleiben unsichtbar in den Spalten gespeichert — du kannst sie jederzeit abrufen oder als Faktor sichtbar machen.</p>
</div>
</div>
<p>Falls du Daten in anderen Formaten brauchst, gibt es passende Geschwister-Funktionen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/read_stata.html">read_stata</a></span><span class="op">(</span><span class="st">"datei.dta"</span><span class="op">)</span>     <span class="co"># Stata</span></span>
<span><span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/read_sas.html">read_sas</a></span><span class="op">(</span><span class="st">"datei.sas7bdat"</span><span class="op">)</span>  <span class="co"># SAS</span></span>
<span><span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/read_xlsx.html">read_xlsx</a></span><span class="op">(</span><span class="st">"datei.xlsx"</span><span class="op">)</span>     <span class="co"># Excel</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Und wenn du einen bearbeiteten Datensatz zurück nach SPSS exportieren möchtest:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/write_spss.html">write_spss</a></span><span class="op">(</span><span class="va">allbus</span>, <span class="st">"allbus_bearbeitet.sav"</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="erster-blick-auf-den-datensatz" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="erster-blick-auf-den-datensatz">
<span class="header-section-number">4.4</span> Erster Blick auf den Datensatz</h2>
<p>Bei knapp 600 Variablen ist es unmöglich, sich alles in der Konsole anzeigen zu lassen. Drei Werkzeuge helfen dir bei der Orientierung:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">)</span>           <span class="co"># kompakte Strukturübersicht</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">)</span>              <span class="co"># Anzahl Fälle</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">)</span>              <span class="co"># Anzahl Variablen</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="variablen-finden-mit-find_var" class="level3" data-number="4.4.1"><h3 data-number="4.4.1" class="anchored" data-anchor-id="variablen-finden-mit-find_var">
<span class="header-section-number">4.4.1</span> Variablen finden mit <code>find_var()</code>
</h3>
<p>Die Variablennamen im ALLBUS sind kryptisch (<code>mm01</code>, <code>pa29</code>, <code>wghtpew</code>). Was wirklich gemessen wird, steht im <strong>Variablenlabel</strong>. mariposas <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code> durchsucht beide gleichzeitig — Name und Label — und liefert dir die Treffer als kleine Übersichtstabelle:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var</a></span><span class="op">(</span><span class="st">"muslim"</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col name                                    label
1 194 mm03 ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT
2 196 mm05   MUSLIMISCHER BUERGERMEISTER IN ORDNUNG
3 197 mm06 UNTER MUSLIMEN SIND VIELE REL. FANATIKER</code></pre>
</div>
</div>
<p>Damit findest du die sechs <code>mm</code>-Items für unsere Islamfeindlichkeits-Skala. Standardmäßig wird in Namen <em>und</em> Labels gesucht; mit <code>search = "label"</code> schränkst du auf Labels ein, mit <code>search = "name"</code> auf Namen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var</a></span><span class="op">(</span><span class="st">"alter"</span>, search <span class="op">=</span> <span class="st">"label"</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   col    name                                    label
1   93     age                       ALTER: BEFRAGTE(R)
2   94    agec        ALTER: BEFRAGTE(R), KATEGORISIERT
3  265    is01 PERSOENLICH.ALTERSSICHERUNG AUSREICHEND?
4  311   dw12a      BEFR.: ALTER BEI AUFGABE DES BERUFS
5  333   scage         GEGENWAERTIGER EHEPARTNER: ALTER
6  334  scagec   GEGENWAERTIGER EHEPARTNER: ALTER, KAT.
7  367    page                     LEBENSPARTNER: ALTER
8  368   pagec               LEBENSPARTNER: ALTER, KAT.
9  434  hh2age                    2.HAUSH.PERSON: ALTER
10 439  hh3age                    3.HAUSH.PERSON: ALTER
11 444  hh4age                    4.HAUSH.PERSON: ALTER
12 449  hh5age                    5.HAUSH.PERSON: ALTER
13 454  hh6age                    6.HAUSH.PERSON: ALTER
14 459  hh7age                    7.HAUSH.PERSON: ALTER
15 464  hh8age                    8.HAUSH.PERSON: ALTER
16 471    dh17        ALTER JUENGSTES HAUSHALTSMITGLIED
17 480  kh1age               ALTER, 1.KIND, AUSSER HAUS
18 483  kh2age               ALTER, 2.KIND, AUSSER HAUS
19 486  kh3age               ALTER, 3.KIND, AUSSER HAUS
20 489  kh4age               ALTER, 4.KIND, AUSSER HAUS
21 492  kh5age               ALTER, 5.KIND, AUSSER HAUS
22 495  kh6age               ALTER, 6.KIND, AUSSER HAUS
23 498  kh7age               ALTER, 7.KIND, AUSSER HAUS
24 501  kh8age               ALTER, 8.KIND, AUSSER HAUS
25 504  kh9age               ALTER, 9.KIND, AUSSER HAUS
26 507 kh10age              ALTER, 10.KIND, AUSSER HAUS
27 573    xi03                   INTERVIEWER(IN): ALTER</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var</a></span><span class="op">(</span><span class="st">"^mm"</span>, search <span class="op">=</span> <span class="st">"name"</span><span class="op">)</span>     <span class="co"># regex: alle mm-Items</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col name                                    label
1 170 mm07        FUER DEN BAU VON MOSCHEEN IN BRD?
2 192 mm01 ISLAMAUSUEBUNG IN DEUTSCHL. BESCHRAENKEN
3 193 mm02 ISLAM PASST IN DIE DEUTSCHE GESELLSCHAFT
4 194 mm03 ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT
5 195 mm04   STAAT SOLLTE ISLAM. GRUPPEN BEOBACHTEN
6 196 mm05   MUSLIMISCHER BUERGERMEISTER IN ORDNUNG
7 197 mm06 UNTER MUSLIMEN SIND VIELE REL. FANATIKER</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>SPSS → R.</strong> In SPSS kennst du <code>DISPLAY DICTIONARY</code> für eine Gesamtübersicht. <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code> ist gezielter: du suchst nach einem inhaltlichen Stichwort und bekommst sofort die passenden Variablen — selbst wenn du die kryptischen Namen nicht im Kopf hast.</p>
</div>
</div>
</section><section id="detail-übersicht-mit-codebook" class="level3" data-number="4.4.2"><h3 data-number="4.4.2" class="anchored" data-anchor-id="detail-übersicht-mit-codebook">
<span class="header-section-number">4.4.2</span> Detail-Übersicht mit <code>codebook()</code>
</h3>
<p>Für eine <em>bestimmte</em> Auswahl von Variablen liefert <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code> aus mariposa eine schöne HTML-Übersicht mit Labels, Ausprägungen und Häufigkeiten. Das ist das R-Äquivalent zum SPSS-<code>DISPLAY DICTIONARY</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook</a></span><span class="op">(</span><span class="va">mm01</span>, <span class="va">mm02</span>, <span class="va">mm03</span>, <span class="va">mm04</span>, <span class="va">mm05</span>, <span class="va">mm06</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>SPSS → R: Dateninspektion.</strong> | SPSS | R | | ——————————- | ——————————– | | <code>FREQUENCIES VARIABLES=mm01.</code> | <code>allbus \|&gt; frequency(mm01)</code> | | <code>DESCRIPTIVES VARIABLES=age.</code> | <code>allbus \|&gt; describe(age)</code> | | <code>DISPLAY DICTIONARY.</code> | <code>allbus \|&gt; codebook(...)</code> |</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reviewer-Hinweis.</strong> In einer Methodenbeschreibung gehört zu jeder Skala ein Mini-Codebook: Wortlaut der Items, Antwortformat, Missing-Behandlung, N pro Item. Wer das in <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code> als Tabelle generiert und in den Anhang seines Berichts schreibt, hat den Forschungsstandard erfüllt.</p>
</div>
</div>
</section></section><section id="variablen-und-fälle-auswählen" class="level2" data-number="4.5"><h2 data-number="4.5" class="anchored" data-anchor-id="variablen-und-fälle-auswählen">
<span class="header-section-number">4.5</span> Variablen und Fälle auswählen</h2>
<p>Die <code>dplyr</code>-Funktionen <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> und <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> sind dein tägliches Werkzeug, um aus einem großen Datensatz das herauszuholen, was du gerade brauchst.</p>
<section id="variablen-auswählen-mit-select" class="level3" data-number="4.5.1"><h3 data-number="4.5.1" class="anchored" data-anchor-id="variablen-auswählen-mit-select">
<span class="header-section-number">4.5.1</span> Variablen auswählen mit <code>select()</code>
</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mm01</span>, <span class="va">mm02</span>, <span class="va">mm03</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,246 × 3
   mm01                        mm02                        mm03              
   &lt;dbl+lbl&gt;                   &lt;dbl+lbl&gt;                   &lt;dbl+lbl&gt;         
 1     5 [..]                      3 [..]                      4 [..]        
 2 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]
 3 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]
 4 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]
 5     2 [..]                      4 [..]                      4 [..]        
 6     3 [..]                      3 [..]                      3 [..]        
 7 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]
 8 NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]          NA(b) [TNZ: SPLIT]
 9     1 [STIMME GAR NICHT ZU]     6 [..]                      2 [..]        
10     7 [STIMME VOLL+GANZ ZU]     1 [STIMME GAR NICHT ZU]     3 [..]        
# ℹ 5,236 more rows</code></pre>
</div>
</div>
<p>Du kannst Bereiche mit <code>:</code> angeben und Variablen mit <code>-</code> ausschließen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mm01</span><span class="op">:</span><span class="va">mm06</span>, <span class="va">eastwest</span>, <span class="va">sex</span>, <span class="va">age</span>, <span class="va">educ</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,246 × 10
   mm01              mm02        mm03        mm04        mm05        mm06       
   &lt;dbl+lbl&gt;         &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;  
 1     5 [..]            3 [..]      4 [..]      2 [..]      6 [..]      2 [..] 
 2 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…
 3 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…
 4 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…
 5     2 [..]            4 [..]      4 [..]      3 [..]      3 [..]      6 [..] 
 6     3 [..]            3 [..]      3 [..]      7 [STI…     6 [..]      3 [..] 
 7 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…
 8 NA(b) [TNZ: SPLI… NA(b) [TNZ… NA(b) [TNZ… NA(b) [TNZ… NA(a) [TNZ… NA(a) [TNZ…
 9     1 [STIMME GA…     6 [..]      2 [..]      1 [STI…     7 [STI…     2 [..] 
10     7 [STIMME VO…     1 [STI…     3 [..]      6 [..]      1 [STI…     7 [STI…
# ℹ 5,236 more rows
# ℹ 4 more variables: eastwest &lt;dbl+lbl&gt;, sex &lt;dbl+lbl&gt;, age &lt;dbl+lbl&gt;,
#   educ &lt;dbl+lbl&gt;</code></pre>
</div>
</div>
<p>Diese Auswahl — die sechs Skalen-Items plus Demografie — ist genau das, was du für die Mini-Studie brauchst.</p>
<p>Zwei nahe Verwandte von <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>:</p>
<ul>
<li>
<strong><code>pull(var)</code></strong> zieht eine einzelne Spalte als reinen Vektor heraus — nützlich, wenn du den Spalteninhalt direkt in eine Funktion füttern willst, die kein Tibble erwartet: <code>allbus |&gt; pull(age) |&gt; mean(na.rm = TRUE)</code>.</li>
<li>
<strong><code>relocate(var, .before = X, .after = Y)</code></strong> sortiert Spalten um, ohne welche zu entfernen — praktisch, wenn die wichtigsten Variablen vorne stehen sollen: <code>allbus |&gt; relocate(islamophobie, populismus, .before = sex)</code>.</li>
</ul></section><section id="fälle-filtern-mit-filter" class="level3" data-number="4.5.2"><h3 data-number="4.5.2" class="anchored" data-anchor-id="fälle-filtern-mit-filter">
<span class="header-section-number">4.5.2</span> Fälle filtern mit <code>filter()</code>
</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sex</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">age</span>, <span class="va">educ</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,672 × 3
   sex       age       educ                  
   &lt;dbl+lbl&gt; &lt;dbl+lbl&gt; &lt;dbl+lbl&gt;             
 1 2 [FRAU]  69        4 [FACHHOCHSCHULREIFE]
 2 2 [FRAU]  18        5 [HOCHSCHULREIFE]    
 3 2 [FRAU]  45        5 [HOCHSCHULREIFE]    
 4 2 [FRAU]  26        3 [MITTLERE REIFE]    
 5 2 [FRAU]  71        2 [VOLKS-,HAUPTSCHULE]
 6 2 [FRAU]  66        2 [VOLKS-,HAUPTSCHULE]
 7 2 [FRAU]  39        3 [MITTLERE REIFE]    
 8 2 [FRAU]  51        3 [MITTLERE REIFE]    
 9 2 [FRAU]  29        5 [HOCHSCHULREIFE]    
10 2 [FRAU]  60        4 [FACHHOCHSCHULREIFE]
# ℹ 2,662 more rows</code></pre>
</div>
</div>
<p>Die Vergleichs- und Logik-Operatoren aus <a href="03-ProgrammierspracheR.html#sec-operatoren" class="quarto-xref"><span>Kapitel 3.4</span></a> (<code>==</code>, <code>!=</code>, <code>&lt;</code>, <code>&gt;</code>, <code>&amp;</code>, <code>|</code>, <code>%in%</code>) bilden hier dein Vokabular. Komplexere Filter kombinierst du frei:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">eastwest</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">&amp;</span> <span class="va">age</span> <span class="op">&gt;=</span> <span class="fl">30</span> <span class="op">&amp;</span> <span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">60</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">eastwest</span>, <span class="va">age</span>, <span class="va">educ</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 825</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warnung
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Vorsicht: Fehlende Werte.</strong> <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> schließt Fälle mit <code>NA</code> in der Bedingung automatisch aus. Das ist meist gewünscht, kann dich aber überraschen. Mit <code>filter(is.na(variable))</code> filterst du gezielt <em>fehlende</em> Werte heraus.</p>
</div>
</div>
</section><section id="fälle-sortieren-mit-arrange" class="level3" data-number="4.5.3"><h3 data-number="4.5.3" class="anchored" data-anchor-id="fälle-sortieren-mit-arrange">
<span class="header-section-number">4.5.3</span> Fälle sortieren mit <code>arrange()</code>
</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">educ</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  age       educ                  
  &lt;dbl+lbl&gt; &lt;dbl+lbl&gt;             
1 18        5 [HOCHSCHULREIFE]    
2 18        5 [HOCHSCHULREIFE]    
3 18        3 [MITTLERE REIFE]    
4 18        1 [OHNE ABSCHLUSS]    
5 18        2 [VOLKS-,HAUPTSCHULE]</code></pre>
</div>
</div>
<p>Absteigend mit <code><a href="https://dplyr.tidyverse.org/reference/desc.html">desc()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">educ</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  age       educ                  
  &lt;dbl+lbl&gt; &lt;dbl+lbl&gt;             
1 99        2 [VOLKS-,HAUPTSCHULE]
2 97        5 [HOCHSCHULREIFE]    
3 97        5 [HOCHSCHULREIFE]    
4 94        2 [VOLKS-,HAUPTSCHULE]
5 94        4 [FACHHOCHSCHULREIFE]</code></pre>
</div>
</div>
</section></section><section id="datentypen-verstehen" class="level2" data-number="4.6"><h2 data-number="4.6" class="anchored" data-anchor-id="datentypen-verstehen">
<span class="header-section-number">4.6</span> Datentypen verstehen</h2>
<p>Wenn du in SPSS arbeitest, fragst du dich selten, <em>welcher Typ</em> eine Variable ist. SPSS macht das im Hintergrund: eine Variable ist „numerisch” oder „string”, und Wertelabels („1 = Mann, 2 = Frau”) sind nur eine Beschriftungs-Schicht obendrauf. In R ist das ein bisschen anders — und am Anfang verwirrend.</p>
<p>R kennt eine ganze Reihe von Datentypen: reine Zahlen (<code>numeric</code>), Text (<code>character</code>), Logik (<code>logical</code>), Kategorien mit fester Reihenfolge (<code>factor</code>). Beim Einlesen eines SPSS-Datensatzes kommt noch ein vierter Typ hinzu, den mariposa von haven übernimmt: <code>&lt;haven_labelled&gt;</code>. Das ist eine Art <em>Hybrid</em>: Die Spalte verhält sich nach außen wie eine Zahl, aber im Hintergrund tragen die Werte ihre SPSS-Wertelabels mit. So bleibt die Information „1 bedeutet Mann” erhalten, ohne dass du sie aus dem Codebook nachschlagen musst.</p>
<p>Mit <code><a href="https://rdrr.io/r/base/class.html">class()</a></code> siehst du den Typ einer Variable:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">$</span><span class="va">sex</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">$</span><span class="va">age</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
</div>
<p>Drei Konvertierungen wirst du immer wieder brauchen:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead><tr class="header">
<th>Funktion</th>
<th>Wirkung</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>to_label(data, var)</code></td>
<td>wandelt <code>&lt;haven_labelled&gt;</code> in einen <strong>Faktor</strong> mit den Wertelabels als Stufen — Standard, wenn du in <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code>-Achsen lesbare Beschriftungen willst</td>
</tr>
<tr class="even">
<td><code>to_numeric(data, var)</code></td>
<td>wandelt in einen reinen numerischen Vektor — Labels gehen verloren</td>
</tr>
<tr class="odd">
<td><code>to_labelled(data, var, labels = ...)</code></td>
<td>wandelt umgekehrt einen Faktor zurück in ein <code>&lt;haven_labelled&gt;</code>
</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/to_label.html">to_label</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">eastwest</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">eastwest</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  sex   eastwest          
  &lt;fct&gt; &lt;fct&gt;             
1 MANN  ALTE BUNDESLAENDER
2 MANN  ALTE BUNDESLAENDER
3 FRAU  ALTE BUNDESLAENDER</code></pre>
</div>
</div>
<p>Wenn du nur Labels <em>abstreifen</em> willst (z. B. weil eine Funktion mit labelled-Vektoren nicht klarkommt), nimmst du <code><a href="https://YannickDiehl.github.io/mariposa/reference/unlabel.html">unlabel()</a></code>: <code>allbus |&gt; unlabel(sex, age)</code>. Selten gebraucht, aber gut zu wissen, wenn ein fremdes Paket sich quer stellt.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hintergrund: Warum nicht einfach Faktor?</strong> In SPSS sind Variablen entweder numerisch oder <em>string</em>. Wertelabels sind ein Zusatz. In R gibt es Faktoren (Kategorien) und numerische Vektoren als getrennte Typen. <code>&lt;haven_labelled&gt;</code> ist eine Brücke: Du arbeitest mit Zahlen, aber die Wertelabels reisen mit. Wann du das auflösen solltest:</p>
<ul>
<li>
<strong><code><a href="https://YannickDiehl.github.io/mariposa/reference/to_label.html">to_label()</a></code></strong> wenn du sortierst, gruppierst, kreuztabellierst oder plottest — Faktoren liefern lesbare Outputs.</li>
<li>
<strong><code><a href="https://YannickDiehl.github.io/mariposa/reference/to_numeric.html">to_numeric()</a></code></strong> wenn du rechnest oder skalierst — z. B. bei Likert-Items, die du als pseudo-metrisch behandelst.</li>
<li>
<strong>Beim Original lassen</strong>, wenn die Variable noch nicht final ist und du das Label später noch brauchst.</li>
</ul>
</div>
</div>
</section><section id="variablen--und-wertelabels-lesen-und-setzen" class="level2" data-number="4.7"><h2 data-number="4.7" class="anchored" data-anchor-id="variablen--und-wertelabels-lesen-und-setzen">
<span class="header-section-number">4.7</span> Variablen- und Wertelabels lesen und setzen</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead><tr class="header">
<th>Funktion</th>
<th>Wirkung</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>var_label(data)</code></td>
<td>Variablenlabels auslesen</td>
</tr>
<tr class="even">
<td><code>var_label(data) &lt;- list(var = "Neue Beschriftung")</code></td>
<td>Variablenlabel setzen</td>
</tr>
<tr class="odd">
<td><code>val_labels(data)</code></td>
<td>Wertelabels auslesen</td>
</tr>
<tr class="even">
<td><code>drop_labels(data)</code></td>
<td>Alle Wertelabels entfernen, deren Ausprägung in den Daten gar nicht vorkommt</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mm01</span>, <span class="va">mm02</span>, <span class="va">mm03</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/var_label.html">var_label</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      mm01 
"ISLAMAUSUEBUNG IN DEUTSCHL. BESCHRAENKEN" 
                                      mm02 
"ISLAM PASST IN DIE DEUTSCHE GESELLSCHAFT" 
                                      mm03 
"ANWESENHEIT VON MUSLIMEN BRINGT KONFLIKT" </code></pre>
</div>
</div>
<p>Das Ergebnis ist ein <strong>benannter Character-Vektor</strong> — pro Variable das hinterlegte Label. So liest du, was eine kryptische Variable wie <code>mm01</code> eigentlich bedeutet, ohne ins Codebook zu schauen.</p>
</section><section id="fehlende-werte-deklarieren" class="level2" data-number="4.8"><h2 data-number="4.8" class="anchored" data-anchor-id="fehlende-werte-deklarieren">
<span class="header-section-number">4.8</span> Fehlende Werte deklarieren</h2>
<p>Fehlende Werte sind in der Sozialforschung Normalität, nicht Ausnahme. Niemand beantwortet jede Frage einer Umfrage — manche überspringen einzelne Punkte, manche wissen es schlicht nicht, manche bekommen wegen eines Split-Designs bestimmte Fragen gar nicht vorgelegt. Und manche Antworten waren ursprünglich da, gingen aber durch einen Datenfehler verloren.</p>
<p>Die GESIS unterscheidet in ALLBUS deshalb <em>vier</em> Arten von fehlenden Werten und kodiert sie mit klar unterscheidbaren negativen Zahlen:</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;">Code</th>
<th>Bedeutung</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>-42</code></td>
<td>DATENFEHLER</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>-11</code></td>
<td>TNZ (trifft nicht zu / Split-Modul)</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>-9</code></td>
<td>KEINE ANGABE</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>-8</code></td>
<td>WEISS NICHT</td>
</tr>
</tbody>
</table>
<p>Die Unterscheidung ist <em>inhaltlich wichtig</em>: ein „weiß nicht” ist methodisch etwas anderes als eine verweigerte Antwort, und ein „trifft nicht zu” (jemand hat die Frage gar nicht gestellt bekommen) ist wiederum etwas anderes als ein echter Datenfehler. Wenn du diese Codes als reguläre Zahlen behandelst — was passiert, wenn du sie einfach in einen Mittelwert wirfst — sind deine Ergebnisse Müll: ein „Durchschnittswert” von <code>-3.4</code> für Lebenszufriedenheit ist offensichtlich Unsinn.</p>
<p>Beim Einlesen werden diese in SPSS als <em>user-missing</em> deklarierten Codes automatisch zu <strong>tagged NAs</strong>. „Tagged” heißt: sie zählen in Berechnungen als <code>NA</code> (also fehlend), behalten aber im Hintergrund die Information, <em>welcher</em> Missing-Typ sie sind. Du kannst sie also später trotzdem voneinander unterscheiden — etwa um zu zeigen, wie viele Personen „weiß nicht” gewählt haben.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hintergrund: Split-Designs im ALLBUS.</strong> Manche Itembatterien werden nur einer Hälfte der Stichprobe gestellt (Code <code>-11</code> für die andere Hälfte). Das gilt insbesondere für die <code>mm</code>-Items unserer Islamfeindlichkeits-Skala. Die effektive N für solche Splits liegt deshalb bei rund 2.500 statt 5.246 — methodisch <em>kein</em> Fehler, sondern Stichproben­architektur. In der Methodenbeschreibung gehört dieser Punkt erwähnt.</p>
</div>
</div>
<p>Wie viele Fälle pro Missing-Code in einer konkreten Variable stecken, zeigt dir <code><a href="https://YannickDiehl.github.io/mariposa/reference/na_frequencies.html">na_frequencies()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/na_frequencies.html">na_frequencies</a></span><span class="op">(</span><span class="va">allbus</span><span class="op">$</span><span class="va">mm01</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   tag    n code            label
1    b 1647  -11       TNZ: SPLIT
2    d  123   -8      WEISS NICHT
3    c   73   -9     KEINE ANGABE
4    a    2  -42 DATENFEHLER: MFN
5 &lt;NA&gt;    0 &lt;NA&gt; (System Missing)</code></pre>
</div>
</div>
<p>Du siehst die Aufschlüsselung: wie viele „weiß nicht”, wie viele „keine Angabe”, wie viele „trifft nicht zu” — alles in einem Aufruf. Praktisch, bevor du entscheidest, ob du bestimmte Codes als reguläre Werte behältst oder als endgültige Missings behandelst.</p>
<p>Wenn du eine Variable hast, in der bestimmte Werte <em>erst nachträglich</em> als fehlend gelten sollen — etwa Altersangaben über 100 als unplausibel —, deklarierst du sie mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/set_na.html">set_na()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/set_na.html">set_na</a></span><span class="op">(</span><span class="va">age</span>, na_values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">9</span>, <span class="op">-</span><span class="fl">8</span><span class="op">)</span>, verbose <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Mit <code>verbose = TRUE</code> zeigt mariposa dir an, wie viele Fälle pro Wert zu <code>NA</code> wurden — kontrolliert und nachvollziehbar.</p>
<p>Mit <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code> (aus tidyr) entfernst du Fälle mit <code>NA</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mm01</span>, <span class="va">mm02</span>, <span class="va">mm03</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3285</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warnung
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Vorsicht: Listenweiser Ausschluss.</strong> <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code> schließt Fälle aus, sobald <em>eine</em> der ausgewählten Variablen <code>NA</code> ist. Das ist klassischer <em>listwise deletion</em>. Wenn du in einer großen Pipeline mit vielen Variablen <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code> rufst, kann deine Fallzahl drastisch schrumpfen. Setze <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code> deshalb gezielt auf die Variablen, die du wirklich brauchst.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hintergrund: MCAR, MAR, MNAR.</strong> Die Methodenliteratur unterscheidet drei Missing-Mechanismen: <em>Missing Completely at Random</em> (Zufall, keine Verzerrung), <em>Missing at Random</em> (Zufall bedingt durch beobachtete Variablen, durch Modellierung korrigierbar) und <em>Missing Not at Random</em> (systematisch, schwer zu beheben). In Survey-Daten wie ALLBUS ist MAR der Regelfall; einfache Listwise Deletion (<code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na()</a></code>) ist dann ein konservativer, aber transparenter Umgang. Imputationsverfahren (z. B. <code>mice</code>) sind die nächste Ausbaustufe — für ein Einsteigerbuch jedoch zu viel.</p>
</div>
</div>
</section><section id="übungen" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="übungen">Übungen</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Übung 1 · Variablen finden · Reproduktion">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Übung 1 · Variablen finden · Reproduktion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Du willst eine Skala zu Vertrauen in Institutionen bauen, kennst aber die Variablennamen nicht auswendig. Nutze <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code>, um (a) alle Variablen mit „vertrau” im Label und (b) alle Variablen mit <code>st</code> am Namensanfang zu finden.</p>
<hr>
<p><strong>Lösung</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var</a></span><span class="op">(</span><span class="st">"vertrau"</span>, search <span class="op">=</span> <span class="st">"label"</span><span class="op">)</span></span>
<span><span class="va">allbus</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var</a></span><span class="op">(</span><span class="st">"^st"</span>, search <span class="op">=</span> <span class="st">"name"</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Übung 2 · Codebook der politischen Vertrauens-Items · Reproduktion">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Übung 2 · Codebook der politischen Vertrauens-Items · Reproduktion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Erstelle ein <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code> für die Items <code>pt01</code> bis <code>pt08</code> (Vertrauen in verschiedene Institutionen). Schau dir Labels und Wertelabels an.</p>
<hr>
<p><strong>Lösung</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook</a></span><span class="op">(</span><span class="va">pt01</span>, <span class="va">pt02</span>, <span class="va">pt03</span>, <span class="va">pt04</span>, <span class="va">pt05</span>, <span class="va">pt06</span>, <span class="va">pt07</span>, <span class="va">pt08</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Übung 3 · Analyse-Subset bilden · Transfer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Übung 3 · Analyse-Subset bilden · Transfer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Erstelle einen Datensatz <code>analyse</code>, der nur die für die Mini-Studie nötigen Variablen enthält (<code>mm01:mm06</code>, <code>pa29:pa35</code>, <code>eastwest</code>, <code>sex</code>, <code>age</code>, <code>educ</code>, <code>wghtpew</code>) und nur Fälle, in denen mindestens fünf der sechs <code>mm</code>-Items gültig sind. <em>Tipp: <code>rowSums(!is.na(across(mm01:mm06))) &gt;= 5</code> als Filterkriterium.</em></p>
<hr>
<p><strong>Lösung</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">analyse</span> <span class="op">&lt;-</span> <span class="va">allbus</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mm01</span><span class="op">:</span><span class="va">mm06</span>, <span class="va">pa29</span><span class="op">:</span><span class="va">pa35</span>, <span class="va">eastwest</span>, <span class="va">sex</span>, <span class="va">age</span>, <span class="va">educ</span>, <span class="va">wghtpew</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="va">mm01</span><span class="op">:</span><span class="va">mm06</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">&gt;=</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">analyse</span><span class="op">)</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Übung 4 · Eigene Forschungsfrage · Mini-Forschungsfrage">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Übung 4 · Eigene Forschungsfrage · Mini-Forschungsfrage
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Wähle ein Thema, das dich politik- oder sozialwissenschaftlich interessiert (Migration, Klima, Geschlechterrollen, …). Finde mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code> zwei bis drei Variablen im ALLBUS 2023, die deine Frage beleuchten könnten. Erstelle ein <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code> für deine Auswahl. Beschreibe in 2–3 Sätzen, was du untersuchen würdest und welche Variable als unabhängige bzw. abhängige Variable dienen könnte.</p>
<p><em>Es gibt hier keine Musterlösung — die Übung trainiert das Auffinden und Verstehen von Variablen, nicht eine bestimmte Antwort.</em></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Forschungsjournal: Stand deiner Mini-Studie.</strong> Du hast den ALLBUS 2023 eingelesen und hast die Werkzeuge, um durch 579 Variablen gezielt zu navigieren. Du weißt, was hinter <code>mm01</code> bis <code>mm06</code> steckt (die sechs Islamfeindlichkeits-Items), du kennst die Missing-Codes der GESIS, und du kannst dein Analyse-Subset gezielt zusammenstellen. <strong>Was als Nächstes kommt:</strong> In <a href="05-Datentransformation.html" class="quarto-xref"><span>Kapitel 5</span></a> wandelst du die Rohitems in zwei Skalen um — Islamfeindlichkeit und Populismus.</p>
</div>
</div>
</section><section id="was-du-jetzt-weißt" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="was-du-jetzt-weißt">Was du jetzt weißt</h2>
<ul>
<li>Du liest SPSS-Daten mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/read_spss.html">read_spss()</a></code> ein und behältst Variablen- und Wertelabels.</li>
<li>Du findest Variablen über Name oder Label mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/find_var.html">find_var()</a></code> und holst dir Detail-Codebooks per <code><a href="https://YannickDiehl.github.io/mariposa/reference/codebook.html">codebook()</a></code>.</li>
<li>Du wählst Variablen und Fälle mit <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> aus — und sortierst sie mit <code><a href="https://dplyr.tidyverse.org/reference/relocate.html">relocate()</a></code> um.</li>
<li>Du verstehst den <code>&lt;haven_labelled&gt;</code>-Typ und wandelst ihn bei Bedarf in Faktor oder numerisch.</li>
<li>Du liest und setzt Variablen- und Wertelabels mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/var_label.html">var_label()</a></code> und <code><a href="https://YannickDiehl.github.io/mariposa/reference/val_labels.html">val_labels()</a></code>.</li>
<li>Du erkennst die ALLBUS-Missing-Codes, prüfst sie mit <code><a href="https://YannickDiehl.github.io/mariposa/reference/na_frequencies.html">na_frequencies()</a></code> und schließt Fälle gezielt aus.</li>
</ul>
<p>Im nächsten Kapitel (<a href="05-Datentransformation.html" class="quarto-xref"><span>Kapitel 5</span></a>) lernst du, wie du aus diesen Rohvariablen die zwei Skalen baust, die die Mini-Studie trägt — Islamfeindlichkeit und Populismus.</p>
</section><section id="weiterführend" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="weiterführend">Weiterführend</h2>
<ul>
<li>mariposa-Vignetten <a href="https://yannickdiehl.github.io/mariposa/articles/data-io.html">„Data I/O”</a> und <a href="https://yannickdiehl.github.io/mariposa/articles/labels-and-missing-values.html">„Labels and Missing Values”</a>.</li>
<li>Hadley Wickham &amp; Garrett Grolemund, <a href="https://r4ds.hadley.nz/data-import.html">R for Data Science (2e), Kapitel „Data Import” und „Data Transformation”</a>.</li>
<li>Joseph Larmarange, <a href="https://larmarange.github.io/labelled/">„labelled” Vignetten</a> — vertiefte Auseinandersetzung mit labelled-Datentypen.</li>
<li>GESIS, <a href="https://search.gesis.org/research_data/ZA8901">Datensatzbeschreibung ALLBUS 2023 (ZA8901)</a> — Methodenbericht und Codeplan.</li>
</ul>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03-ProgrammierspracheR.html" class="pagination-link" aria-label="Programmiersprache R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Programmiersprache R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-Datentransformation.html" class="pagination-link" aria-label="Daten transformieren und Skalen bilden">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Daten transformieren und Skalen bilden</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/RLoesung/RWorkshop/edit/main/04-Datenimport.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/RLoesung/RWorkshop/blob/main/04-Datenimport.qmd" class="toc-action"><i class="bi empty"></i>Quellcode anzeigen</a></li><li><a href="https://github.com/RLoesung/RWorkshop/issues/new" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>